quotes = [
"(WHEEZES) (GROANS) (LABORED BREATHING) ",
"A MOST JUDICIOUS PROPOSITION!",
"GODS BE GOOD!!",
"MY WIFE AND SON ARE DEAD!  I WILL NOT SIT HERE AND SUFFER CROWS THAT COME TO FEAST ON THEIR CORPSES!",
"NOW THAT IS A NAME FIT FOR A KING!",
"OTTO HIGHTOWER IS A MORE HONORABLE MAN THAN YOU COULD EVER BE!",
"WHY DO YOU CUT ME SO DEEPLY?",
"WE ARE A FAMILY!",
"WHAT LORD WOULD WED HER NOW?  IN THIS CONDITION!?",
"WHERE DID YOU HEAR SUCH CALUMNIES?  {}!  TELL ME THE TRUTH OF IT!",
"WHERE DID YOU HEAR THIS?!",
"WHERE IN THE SEVEN HELLS IS RHAENYRA?!",
"WOULD YOU LIKE TO SEE THE TAPESTRIES!?",
"YOU WILL ADDRESS ME AS 'YOUR GRACE', OR I WILL HAVE MY KINGSGUARD CUT OUT YOUR TONGUE!",
"YOUR FATHER, YOUR GRANDSIRE, YOUR KING DEMANDS IT.",
"YOUR KING DEMANDS AN ANSWER!  WHO SPOKE THESE LIES TO YOU?!",
"I CAME HERE TO HUNT, NOT TO BE SUFFOCATGED BY ALL THIS FUCKING POLITICKING!",
"EVEN I DO NOT EXIST ABOVE TRADITION AND DUTY, {}!",
"*I would be delighted!*",
"I WILL SIT THE THRONE TODAY.",
"INSTEAD OF BEING BY MY SIDE, YOU CHOSE TO CELEBRATE YOUR OWN RISE, LAUGHING WITH YOUR WHORES AND YOUR LICKSPITTLES!",
"MY HEIR WILL SOON PUT ALL OF THIS DAMNABLE HAND-WRINGING TO REST HIMSELF!",
"I WILL NOT BE MADE TO CHOOSE BETWEEN MY BROTHER AND MY DAUGHTER!",
"*I WILL HAVE YOUR TONGUE FOR THAT!*",
"DAEMON IS MY BROTHER.  MY BLOOD.  AND HE WILL HAVE HIS PLACE AT MY COURT!",
"*A dragon's saddle is one thing, but the Iron Throne is the most dangerous seat in the realm.*",
"*A truly great Targaryen King I am. Powerless over mine own daughter of seven and ten.*",
"*Be welcome! I know many of you have traveled long leagues to be at these games. But I promise, you will not be disappointed!*",
"*Daemon was not made to wear the crown. But I believe that you were, {}.*",
"*Don't be scared. They're going to bring the babe out.*",
"*I did not decide to name Rhaenyra my heir on a whim. All the lord of the kingdom would do well to remember that.* ",
"*You are the very best of your mother. And I believe it, I know she did, that you could be a great ruling queen.*",
"*I must... admit... my confusion.  I do not understand why petitions are being heard over a settled succession.* ",
"*I will not cloud my mind. I must put things right.*",
"*I'm glad we could meet. I know tempers ran hot today, and I wanted to assure you how much I value the bond between our houses.*",
"*I'm going to bed, {}.*",
"What is your advice, dear {}?",
"She's twelve!",
"Ever since my name was read by the archmaesters at the Great Council, I have felt Corlys Velaryon's envious gaze staring at me from across the Blackwater.",
"*It both gladdens my heart and fills me with sorrow to see these faces around the table.*",
"*Let us no longer hold ill feelings in our hearts. The crown cannot stand strong if the House of the Dragon remains divided.*",
"*Mayhaps we can turn our attentions towards happier pursuits.*",
"*{} was a strong Lord Commander of the Kingsguard. But he was ill for some time. He passed in peace, I hope.*",
"*That man's pride has pride.*",
"*The boy just turned two, {}...*",
"This is a lie. You have been lied to.",
"WHO IS RESPONSIBLE FOR THIS GOSSIP? HAVE THIS RUMORMONGER BROUGHT BEFORE ME AT ONCE AND I WILL TAKE THEIR EYES!",
"You think yourself a cunning man. Your designs are obvious.",
"*The Gods punish me for my indulgences.*",
"*The Iron Throne is the most dangerous seat in the realm.* ",
"*The King's cupbearer must not be late. Leaves people wanting for cups.*",
"*The tourney will take the better part of a week. Before the games are over, my son will be born, and the whole realm will celebrate.*",
"*The truth does not matter, {}. Only perception.*",
"*Then he will be loved and cherished.*",
"*So I said to him, 'I believe you may be looking up the wrong end'*",
"*There are times when I would rather face the black dread himself than mine own daughter of seven and ten.*",
"*There's a boy in the Queen's belly. I know it.*",
"**THIS INTERMINABLE INFIGHTING MUST CEASE, ALL OF YOU!**",
"*This is an occasion for celebration, it seems.*",
"*I had a black mare once. Black like a raven. One day, she escaped her pasture and he neighboring stallion sired a foal on her. The stallion was as silver as the moon on a winter's night and the foal, when it was born, chestnut. Just the most unremarkable brown horse you ever saw. Nature is a thing of mysterious works.*",
"*Tongues will not change the succession, let them wag.*",
"*Well... the matter is settled.  Again.  I hereby reaffirm Prince Lucerys of House Velaryon as heir to Driftmark, the Driftwood Throne, and the next Lord of the Tides. (WHEEZING)*",
"*What are you saying? My brother would murder me, take my crown? Are you?!*",
"*Would you like to see the tapestries?*",
"*You are my political headache.*",
"*You are to return to Runestone and your lady wife at once, and you are to do so without quarrel by order of your King.*",
"YOU SPEND MORE TIME IN THAT BATH THAN I DO ON THE THRONE!",
"*Your mother's absence is a wound that will never heal. Without her, the Red Keep has lost a warmth that I dare say it will never recover.*"]

yoinked = [
    "*My own face... is no longer a handsome one...if indeed it ever was.*",
    "*The idea that we control the dragons is an illusion. They're a power man should never have trifled with. One that brought Valyria its doom.*",
"*The glory of old Valyria will never be seen again.* ",
"*Just as Daenys foresaw the end of Valyria, Aegon foresaw the end of the world of men. 'Tis to begin with a terrible winter.*",
]