quotes = [
"(WHEEZES) (GROANS) (LABORED BREATHING) ",
"A dragon's saddle is one thing, but the Iron Throne is the most dangerous seat in the realm. ",
"A MOST JUDICIOUS PROPOSITION!",
"A truly great Targaryen King I am. Powerless over mine own daughter of seven and ten.",
"Balerion was the last living creature to have seen Old Valyria before the Doom. Its greatness and its flaws. When you look at the dragons, what do you see?",
"Be welcome! I know many of you have traveled long leagues to be at these games. But I promise, you will not be disappointed!",
"DAEMON IS MY BROTHER.  MY BLOOD.  AND HE WILL HAVE HIS PLACE AT MY COURT!",
"Daemon was not made to wear the crown. But I believe that you were, {}.",
"Do you think Daemon is distracted by his present tasks? And that his thoughts and energies are occupied?",
"Don't be scared. They're going to bring the babe out.",
"EVEN I DO NOT EXIST ABOVE TRADITION AND DUTY, {}!",
"GODS BE GOOD!!",
"I CAME HERE TO HUNT, NOT TO BE SUFFOCATGED BY ALL THIS FUCKING POLITICKING!",
"I did not decide to name Rhaenyra my heir on a whim. All the lord of the kingdom would do well to remember that. ",
"You are the very best of your mother. And I believe it, I know she did, that you could be a great ruling queen.",
"I must... admit... my confusion.  I do not understand why petitions are being heard over a settled succession. ",
"I will not be made to choose between my brother and my daughter.",
"I will not cloud my mind. I must put things right.",
"I WILL SIT THE THRONE TODAY.",
"I WILL HAVE YOUR TONGUE FOR THAT!",
"I'm glad we could meet. I know tempers ran hot today, and I wanted to assure you how much I value the bond between our houses.",
"I'm going to bed, {}.",
"It both gladdens my heart and fills me with sorrow to see these faces around the table.",
"Just as Daenys foresaw the end of Valyria, Aegon foresaw the end of the world of men. 'Tis to begin with a terrible winter.",
"Let us no longer hold ill feelings in our hearts. The crown cannot stand strong if the House of the Dragon remains divided.",
"Mayhaps we can turn our attentions towards happier pursuits.",
"INSTEAD OF BEING BY MY SIDE, YOU CHOSE TO CELEBRATE YOUR OWN RISE, LAUGHING WITH YOUR WHORES AND YOUR LICKSPITTLES!",
"My heir will soon put all of this damnable hand-wringing to rest himself.",
"My own face... is no longer a handsome one...if indeed it ever was. ",
"MY WIFE AND SON ARE DEAD!  I WILL NOT SIT HERE AND SUFFER CROWS THAT COME TO FEAST ON THEIR CORPSES!",
"Now that is a name fit for a king!",
"Otto Hightower is a more honorable man than you could ever be.",
"{} was a strong Lord Commander of the Kingsguard. But he was ill for some time. He passed in peace, I hope.",
"That man's pride has pride.",
"The boy just turned two, {}…..",
"The crown has heard your report, Lord {}, and takes it under advisement.",
"The glory of old Valyria will never be seen again. ",
"The Gods punish me for my indulgences.",
"The idea that we control the dragons is an illusion. They're a power man should never have trifled with. One that brought Valyria its doom.",
"The Iron Throne is the most dangerous seat in the realm. ",
"The King's cupbearer must not be late. Leaves people wanting for cups.",
"The tourney will take the better part of a week. Before the games are over, my son will be born, and the whole realm will celebrate.",
"The truth does not matter, {}. Only perception. ",
"Then he will be loved and cherished.",
"Would you like to see the tapestries?",
"Why do you cut me so deeply?",
"There are times when I would rather face the black dragon myself than my own daughter of 15. ",
"There's a boy in the Queen's belly. I know it.",
"This interminable infighting must cease, all of you.",
"This is an occasion for celebration, it seems.",
"Tongues will not change the succession, let them wag. ",
"WE ARE A FAMILY!",
"Well... the matter is settled.  Again.  I hereby reaffirm Prince Lucerys of House Velaryon as heir to Driftmark, the Driftwood Throne, and the next Lord of the Tides. (WHEEZING)",
"What are you saying? My brother would murder me, take my crown? Are you?!",
"WHAT LORD WOULD WED HER NOW?  IN THIS CONDITION!?",
"WHERE DID YOU HEAR SUCH CALUMNIES?  {}!  TELL ME THE TRUTH OF IT!",
"WHERE DID YOU HEAR THIS?!",
"WHERE IN THE SEVEN HELLS IS RHAENYRA?!",
"WOULD YOU LIKE TO SEE THE TAPESTRIES!?",
"Would you like to see the tapestries?",
"You are my political headache.",
"You are to return to Runestone and your lady wife at once, and you are to do so without quarrel by order of your King.",
"You spend more time in that bath than I do on the throne.",
"You will address me as 'Your Grace,' or I will have my Kingsguard cut out your tongue.",
"YOUR FATHER, YOUR GRANDSIRE, YOUR KING DEMANDS IT.",
"YOUR KING DEMANDS AN ANSWER!  WHO SPOKE THESE LIES TO YOU?!",
"Your mother's absence is a wound that will never heal. Without her, the Red Keep has lost a warmth that I dare say it will never recover."]