import praw
import os
from dotenv import load_dotenv

load_dotenv()


config = {
    "vizzy-t-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("vizzy_client_id"),
                    client_secret=os.getenv("vizzy_client_secret"),
                    password=os.getenv("vizzy_password"),
                    user_agent=os.getenv("vizzy_user_agent"),
                    username=os.getenv("vizzy_username")
                ),
        "webhook": os.getenv("vizzy_webhook"),
        "keywords": ["vizzy t", "vissy t"],
        "subs": "FreeFolkSimulator",
        "db": "vizzy_comments",
        "quotes": [
            "(WHEEZES) (GROANS) (LABORED BREATHING) ",
            "A MOST JUDICIOUS PROPOSITION!",
            "GODS BE GOOD!!",
            "MY WIFE AND SON ARE DEAD!  I WILL NOT SIT HERE AND SUFFER CROWS THAT COME TO FEAST ON THEIR CORPSES!",
            "NOW THAT IS A NAME FIT FOR A KING!",
            "OTTO HIGHTOWER IS A MORE HONORABLE MAN THAN YOU COULD EVER BE!",
            "WHY DO YOU CUT ME SO DEEPLY?",
            "WE ARE A FAMILY!",
            "WHAT LORD WOULD WED HER NOW?  IN THIS CONDITION!?",
            "WHERE DID YOU HEAR SUCH CALUMNIES?  {}!  TELL ME THE TRUTH OF IT!",
            "WHERE DID YOU HEAR THIS?!",
            "WHERE IN THE SEVEN HELLS IS RHAENYRA?!",
            "WOULD YOU LIKE TO SEE THE TAPESTRIES!?",
            "YOU WILL ADDRESS ME AS 'YOUR GRACE', OR I WILL HAVE MY KINGSGUARD CUT OUT YOUR TONGUE!",
            "YOUR FATHER, YOUR GRANDSIRE, YOUR KING DEMANDS IT.",
            "YOUR KING DEMANDS AN ANSWER!  WHO SPOKE THESE LIES TO YOU?!",
            "I CAME HERE TO HUNT, NOT TO BE SUFFOCATED BY ALL THIS FUCKING POLITICKING!",
            "EVEN I DO NOT EXIST ABOVE TRADITION AND DUTY, {}!",
            "*I would be delighted!*",
            "I WILL SIT THE THRONE TODAY.",
            "INSTEAD OF BEING BY MY SIDE, YOU CHOSE TO CELEBRATE YOUR OWN RISE, LAUGHING WITH YOUR WHORES AND YOUR LICKSPITTLES!",
            "MY HEIR WILL SOON PUT ALL OF THIS DAMNABLE HAND-WRINGING TO REST HIMSELF!",
            "I WILL NOT BE MADE TO CHOOSE BETWEEN MY BROTHER AND MY DAUGHTER!",
            "*I WILL HAVE YOUR TONGUE FOR THAT!*",
            "DAEMON IS MY BROTHER.  MY BLOOD.  AND HE WILL HAVE HIS PLACE AT MY COURT!",
            "*A dragon's saddle is one thing, but the Iron Throne is the most dangerous seat in the realm.*",
            "*A truly great Targaryen King I am. Powerless over mine own daughter of seven and ten.*",
            "*Be welcome! I know many of you have traveled long leagues to be at these games. But I promise, you will not be disappointed!*",
            "*Daemon was not made to wear the crown. But I believe that you were, {}.*",
            "*Don't be scared. They're going to bring the babe out.*",
            "*I did not decide to name Rhaenyra my heir on a whim. All the lord of the kingdom would do well to remember that.* ",
            "*You are the very best of your mother. And I believe it, I know she did, that you could be a great ruling queen.*",
            "*I must... admit... my confusion.  I do not understand why petitions are being heard over a settled succession.* ",
            "*I will not cloud my mind. I must put things right.*",
            "*I'm glad we could meet. I know tempers ran hot today, and I wanted to assure you how much I value the bond between our houses.*",
            "*I'm going to bed, {}.*",
            "What is your advice, dear {}?",
            "She's twelve!",
            "Ever since my name was read by the archmaesters at the Great Council, I have felt Corlys Velaryon's envious gaze staring at me from across the Blackwater.",
            "*It both gladdens my heart and fills me with sorrow to see these faces around the table.*",
            "*Let us no longer hold ill feelings in our hearts. The crown cannot stand strong if the House of the Dragon remains divided.*",
            "*Mayhaps we can turn our attentions towards happier pursuits.*",
            "*{} was a strong Lord Commander of the Kingsguard. But he was ill for some time. He passed in peace, I hope.*",
            "*That man's pride has pride.*",
            "*The boy just turned two, {}...*",
            "This is a lie. You have been lied to.",
            "WHO IS RESPONSIBLE FOR THIS GOSSIP? HAVE THIS RUMORMONGER BROUGHT BEFORE ME AT ONCE AND I WILL TAKE THEIR EYES!",
            "You think yourself a cunning man. Your designs are obvious.",
            "*The Gods punish me for my indulgences.*",
            "*The Iron Throne is the most dangerous seat in the realm.* ",
            "*The King's cupbearer must not be late. Leaves people wanting for cups.*",
            "*The tourney will take the better part of a week. Before the games are over, my son will be born, and the whole realm will celebrate.*",
            "*The truth does not matter, {}. Only perception.*",
            "*Then he will be loved and cherished.*",
            "*So I said to him, 'I believe you may be looking up the wrong end'*",
            "*There are times when I would rather face the black dread himself than mine own daughter of seven and ten.*",
            "*There's a boy in the Queen's belly. I know it.*",
            "**THIS INTERMINABLE INFIGHTING MUST CEASE, ALL OF YOU!**",
            "*This is an occasion for celebration, it seems.*",
            "*I had a black mare once. Black like a raven. One day, she escaped her pasture and he neighboring stallion sired a foal on her. The stallion was as silver as the moon on a winter's night and the foal, when it was born, chestnut. Just the most unremarkable brown horse you ever saw. Nature is a thing of mysterious works.*",
            "*Tongues will not change the succession, let them wag.*",
            "*Well... the matter is settled.  Again.  I hereby reaffirm Prince Lucerys of House Velaryon as heir to Driftmark, the Driftwood Throne, and the next Lord of the Tides. (WHEEZING)*",
            "*What are you saying? My brother would murder me, take my crown? Are you?!*",
            "*Would you like to see the tapestries?*",
            "*You are my political headache.*",
            "*You are to return to Runestone and your lady wife at once, and you are to do so without quarrel by order of your King.*",
            "YOU SPEND MORE TIME IN THAT BATH THAN I DO ON THE THRONE!",
            "*Your mother's absence is a wound that will never heal. Without her, the Red Keep has lost a warmth that I dare say it will never recover.*"
        ]
    },
    "caraxes-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("caraxes_client_id"),
                    client_secret=os.getenv("caraxes_client_secret"),
                    password=os.getenv("caraxes_password"),
                    user_agent=os.getenv("caraxes_user_agent"),
                    username=os.getenv("caraxes_username")
                ),
        "webhook": os.getenv("caraxes_webhook"),
        "keywords": ["caraxes", "caraxes"],
        "subs": "FreeFolkSimulator",
        "db": "caraxes_comments",
        "quotes": [
            '*EEEEEeeeeEeeEeEEeeeeeee*',
            '**EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE**',
            '*Eeeeee.  Eeeeeee eee eeeee ee eeeeee, eee eeeee.*',
            '*eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee*',
            '**EEEEEEEEEEEEEEEEEEE EEEEEEE EEEEEEEEEEE**'
        ]
    },
    "mad_king_bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("mad_client_id"),
                    client_secret=os.getenv("mad_client_secret"),
                    password=os.getenv("mad_password"),
                    user_agent=os.getenv("mad_user_agent"),
                    username=os.getenv("mad_username")
                ),
        "webhook": os.getenv("mad_webhook"),
        "keywords": ["mad king", "aerys", "stark"],
        "subs": "FreeFolkSimulator",
        "db": "mad_comments",
        "quotes": [
            "BURN THEM ALL!!!",
            "You are my most able servant, u/{}, but a man does not marry his heir to his servant's daughter.",
            "I want him dead, the traitor!",
            "She smelled Dornish.",
            "Let him be the king of ashes!!"
            ]
    },
    "aeggy-3-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("aeggy_client_id"),
                    client_secret=os.getenv("aeggy_client_secret"),
                    password=os.getenv("aeggy_password"),
                    user_agent=os.getenv("aeggy_user_agent"),
                    username=os.getenv("aeggy_username")
                ),
        "webhook": os.getenv("aeggy_webhook"),
        "keywords": ["aeggy", "aegon"],
        "subs": "FreeFolkSimulator",
        "db": "aeggy_comments",
        "quotes": [
            '*gurgles*',
        ]
    },
    "stanny-b-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("stanny_client_id"),
                    client_secret=os.getenv("stanny_client_secret"),
                    password=os.getenv("stanny_password"),
                    user_agent=os.getenv("stanny_user_agent"),
                    username=os.getenv("stanny_username")
                ),
        "webhook": os.getenv("stanny_webhook"),
        "keywords": ["stanny b", "mannis"],
        "subs": "FreeFolkSimulator",
        "db": "stanny_comments",
        "quotes": [
            "It is customary to kneel when surrendering to a king",
            "I'm not so easily killed, men have been trying for years",
            "She's my daughter, you will not strike her",
            "Fewer",
            "A good act does not wash out the bad nor the bad the good.",
            "I don't punish men for bravery, I reward them.",
            "I will not become a page in someone else's history book",
            "Cleaner ways don't win wars",
            "We march to victory or defeat but we go forward, only forward.",
            "COME WITH ME AND TAKE THIS CITY",
            "I never asked for this, no more than I asked to be king. Yet dare I disregard her? We do not choose our destinies. Yet we must ... we must do our duty, no? Great or small, we must do our duty",
            "It is not a question of wanting. The throne is mine, as Robert's heir. That is law. After me, it must pass to my daughter, unless Selyse should finally give me a son. I am king. Wants do not enter into it. I have a duty to my daughter. To the realm. Even to Robert. He loved me but little, I know, yet he was my brother. The Lannister woman gave him horns and made a motley fool of him. She may have murdered him as well, as she murdered Jon Arryn and Ned Stark. For such crimes there must be justice. Starting with Cersei and her abominations. But only starting. I mean to scour that court clean. As Robert should have done after the Trident.",
            "These pardoned lords would do well to reflect on that. Good men and true will fight for Joffrey, wrongly believing him the true king. A northman might even say the same of Robb Stark. But these lords who flocked to my brother's banners knew him for a usurper. They turned their backs on their rightful king for no better reason than dreams of power and glory, and I have marked them for what they are. Pardoned them, yes. Forgiven. But not forgotten",
            "Kings have no friends, only subjects and enemies.",
            "I know the cost! Last night, gazing into that hearth, I saw things in the flames as well. I saw a king, a crown of fire on his brows, burning… burning, Davos. His own crown consumed his flesh and turned him into ash. Do you think I need Melisandre to tell me what that means? Or you?",
            "I never asked for this crown. Gold is cold and heavy on the head, but so long as I am the king, I have a duty... If I must sacrifice one child to the flames to save a million from the dark... Sacrifice... is never easy",
            "We are well rid of her, then. I will not suffer such abominations here. This is not King's Landing.",
            "Lord Seaworth is a man of humble birth, but he reminded me of my duty, when all I could think of was my rights. I had the cart before the horse, Davos said. I was trying to win the throne to save the kingdom, when I should have been trying to save the kingdom to win the throne",
            "Half my army is made up of unbelievers, I will have no burnings, pray harder.",
            "Everyman shall reap what he has sown, from the highest lord to the lowest gutter rat. And some will lose more than the tips of their fingers, I promise you. They have made my kingdom bleed, I do not forget that.",
            "It has always been so. I am not . . . I am not a cruel man, Ser Davos. You know me. Have known me long. This is not my decree. It has always been so, since Aegon's day and before. Daemon Blackfyre, the brothers Toyne, the Vulture King, Grand Maester Hareth . . . traitors have always paid with their lives . . . even Rhaenyra Targaryen. She was daughter to one king and mother to two more, yet she died a traitor's death for trying to usurp her brother's crown. It is law. Law, Davos. Not cruelty.",
            "I defeated your uncle Victarion and his Iron Fleet off Fair Isle, the first time your father crowned himself. I held Storm's End against the power of the Reach for a year, and took Dragonstone from the Targaryens. I smashed Mance Rayder at the Wall, though he had twenty times my numbers. Tell me, turncloak, what battles has the Bastard of Bolton ever won that I should fear him?",
            "We all know what my brother would do. Robert would gallop up to the gates of Winterfell alone, break them with his warhammer, and ride through the rubble to slay Roose Bolton with his left hand and the Bastard with his right. I am not Robert. But we will march, and we will free Winterfell … or die in the attempt.",
            "When I was a lad I found an injured goshawk and nursed her back to health. Proudwing, I named her. She would perch on my shoulder and flutter from room to room after me and take food from my hand, but she would not soar. Time and again I would take her hawking, but she never flew higher than the treetops.",
            "If Renly had done his duty as a brother we would have smashed lord Tywin together. A victory even Robert would have been proud of.",
            "Any of you I would think, even the cook.",
        ]
    },
    "johnny-s-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("jonny_client_id"),
                    client_secret=os.getenv("jonny_client_secret"),
                    password=os.getenv("jonny_password"),
                    user_agent=os.getenv("jonny_user_agent"),
                    username=os.getenv("jonny_username")
                ),
        "webhook": os.getenv("jonny_webhook"),
        "keywords": ["jonny s"],
        "subs": "FreeFolkSimulator",
        "db": "jonny_comments",
        "quotes": [
            "...",
            "[*MY WATCH HAS ENDED*](https://imgur.com/gallery/rhpNzZz)",
            "[*SCREAMS AT DRAGON*](https://tenor.com/view/jon-viserion-dragon-provoke-im-ready-gif-14061942)",
            "AH DON’T WANT ET I NEVER HAVE",
            "Ah dun wannit",
            "AH NEVEH BEEN A STAHRK",
            "AHM A BASTARD",
            "FALL BACK! FALL BACK!",
            "HOW DID YOU SNEAK UP ON ME",
            "I KNOW WHERE TO PUT IT",
            "I WANT YOU TO PROMISE YOU WON'T TELL ANOTHER SOUL",
            "I will not punish sons and daughters for the crimes of their fathers.",
            "I'm not asking you to forget your dead. I'll never forget mine.",
            "MY FATHER WAS NED STARK. I HAVE THE BLOOD OF THE FIRST MEN. MY ANCESTORS LIVED HERE SAME AS YOURS.",
            "She is mah queen",
            "Sometimes there is no happy choice Sam, only one less grievous than the others.",
            "Tell them Bran!",
            "That's the price you pay if you want to be a man of the Night's Watch.",
            "THE ENEMY NEVER TIRES, NEVER STOPS.",
            "The Long Night is coming, and the dead come with it.",
            "THE NIGHT KING IS COMIN'",
            "The war is not over and I promise you, friend, the true enemy won't wait out the storm. He brings the storm.",
            "The White Walkers don't care if a man's free folk or crow. We're all the same to them, meat for their army.",
            "There's no time for all of this",
            "They were born on the wrong side of the wall, that doesn't make them monsters.",
            "WE NEED ALL THE MEN WE CAN GET",
            "WHAT WOULD YOU KNOW OF BEING A BASTARD",
            "Winter is here.",
            "You are mah queen",
            "YOU WERE RIGHT THE WHOLE TIME",
        ]
    },
    "the_hound_bot_": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("hound_client_id"),
                    client_secret=os.getenv("hound_client_secret"),
                    password=os.getenv("hound_password"),
                    user_agent=os.getenv("hound_user_agent"),
                    username=os.getenv("hound_username")
                ),
        "webhook": os.getenv("hound_webhook"),
        "keywords": ["hound","greggy c", "lommy"],
        "subs": "FreeFolkSimulator",
        "db": "hound_comments",
        "quotes": [
            "DANCING? MAYBE YOU OUGHT TO PUT ON A DRESS. WHO TAUGHT YOU THAT SHITE?",
            "ANY BOY WHORE WITH A SWORD COULD BEAT THREE MERYN TRANTS",
            "LOTS OF CUNTS",
            "I ALWAYS THOUGHT YOU ARE DULL AS DIRT",
            "FUCK WATER, BRING ME WINE!",
            "ANY MAN DIES WITH A CLEAN SWORD, I'LL RAPE HIS FUCKING CORPSE!",
            "YOU'RE SHIT AT DYING YOU KNOW THAT?",
            "FUCK THE KING",
            "FOR FUCK'S SAKE, WILL YOU SHUT YOUR HOLE?",
            "YOU WANT TO SUCK MY DICK, IS THAT IT?",
            "I BET YOU DO",
            "WOULD YOU SHUT UP?",
            "I'M GONNA HAVE TO EAT EVERY FUCKING CHICKEN IN THIS ROOM",
            "THERE'S NO DIVINE JUSTICE, YOU DUMB CUNT",
            "I DON'T GIVE TWO SHITS ABOUT WILDLINGS, GINGERS I HATE",
            "FAMILY, HONOR, ALL THAT HORSESHIT. IT'S ALL YOU LORDS AND LADIES EVER TALK ABOUT",
            "YOU THINK YOU'RE FOOLING ANYONE WITH THAT TOP KNOT? YOU BALD CUNT",
            "I'D SKIN YOU ALIVE FOR WINE",
            "WHAT THE FUCK'S A LOMMY?",
            "HANGING? OVER IN AN INSTANT. WHERE'S THE PUNISHMENT IN THAT?",
            "COCK",
        ]
    },
    "olenna-t-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("olenna_t_client_id"),
                    client_secret=os.getenv("olenna_t_client_secret"),
                    password=os.getenv("olenna_t_password"),
                    user_agent=os.getenv("olenna_t_user_agent"),
                    username=os.getenv("olenna_t_username")
                ),
        "webhook": os.getenv("olenna_t_webhook"),
        "keywords": ["olenna","queen of thorns"],
        "subs": "FreeFolkSimulator",
        "db": "olenna_comments",
        "quotes": [
            "(grimacing) Oof, you can smell the shit from five miles away!",
            "A Sword Swallower through and through.",
            "Are there any figs? Fetch some! I always take figs mid-afternoon. Helps move the bowels.",
            "Are you going to bring the food, or do you mean to starve us to death?",
            "Do shut up, Dear.",
            "Get some rest, dear. You look appalling.",
            "GODS boy! That's enough, were not in a tavern!",
            "He really was a cunt, wasn’t he?",
            "I climbed all those steps to discuss financial matters?",
            "I was told you were drunk, impertinent, and thoroughly debauched.",
            "I wonder if you’re the worst person I’ve ever met? At a certain age, It’s hard to recall. But the truly vile do stand out through the years.",
            "Is that your usual line u/{}? Are You here to seduce me? Oh no, please seduce away. It’s been so long! Though... I rather think it’s all for naught. What happens when the nonexistent bumps against the decrepit?",
            "I've known a great number of clever men. I've outlived them all. Do you know how? I ignored them.",
            "Not Now u/{}, Lord Tywin And I Are Speaking.",
            "OLD. I'm something of an expert on the subject.",
            "Tell Cersei. I want her to know it was me.",
            "The cheese will be served when I want it served, and I want it served now.",
            "Well, if it isn't the famous Tart, u/{}.",
            "What is you're name again?? Barbaro???",
            "You look like an angry little boy. Don’t presume to tell me what I need.",
            "You've lost, u/{}. It's the only joy I can find in all this misery.",
        ]
    },
    "karl-t-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("karl_t_client_id"),
                    client_secret=os.getenv("karl_t_client_secret"),
                    password=os.getenv("karl_t_password"),
                    user_agent=os.getenv("karl_t_user_agent"),
                    username=os.getenv("karl_t_username")
                ),
        "webhook": os.getenv("karl_t_webhook"),
        "keywords": ["karl tanner","gin alley"],
        "subs": "FreeFolkSimulator",
        "db": "karl_comments",
        "quotes": [
            "I'd rather eat what you've got hidden away.",
            "You are a bastard. A daughter fooking wildling bastard.",
            "There are no laws beyond the Wall!",
            "Karl Tanner from Gin Alley drinking wine from the skull of Jeor fooking Mormont.",
            "Any command for us, Lord Commander? What's that? Fook 'em 'til they're dead? You hear that, boys? Fook 'em till they're dead!",
            "Go outside and feed the beast.",
            "You should shut your fooking hole, ugly little cunt.",
            "You look like a fooking ballsack. Ugly looking stupid cunt-face. I could piss in any gutter and soak five of you.",
            "You know how much they pay me to kill a man in King's Landing? Seven silvers. They told me a man's name and that man never saw daylight again, none of them cocksuckers got away from me.",
            "I haven't lost a fight since I was nine. Maybe it's time? D'you think? Eh? Maybe you're the man? Eh? Cunt?",
            "I was a fooking legend in Gin Alley. A FOOKING LEGEND! I would take any knight - any knight, anytime! Fooking cunts in steel-plate, fooking cowards!",
            "And here I thought today was going to be another boring day.",
        ]
    },
    "torry-g-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("torry_client_id"),
                    client_secret=os.getenv("torry_client_secret"),
                    password=os.getenv("torry_password"),
                    user_agent=os.getenv("torry_user_agent"),
                    username=os.getenv("torry_username")
                ),
        "webhook": os.getenv("torry_webhook"),
        "keywords": ["tormund","torry g"],
        "subs": "FreeFolkSimulator",
        "db": "tormund_comments",
        "quotes": [
            "['I like you boy'](https://66.media.tumblr.com/c90da354ee2c9885f46ce6ad0464ba6c/tumblr_n1k99bxCgt1se9fcoo1_250.gif)",
            "And after all that. This fucker comes north and takes her from me",
            "And if you fall, don't scream. You don't want that to be the last thing she remembers.",
            "Clegane, my heart is broken",
            "Dick, I like it!",
            "Don't panic, boy. This isn't the damned Night's Watch where we make you swear off girls.",
            "Ghost and I will have fun running free in the true north",
            "Gingers are beautiful. We are kissed by fire.",
            "HE'S PRETTIER THAN BOTH MY DAUGHTERS, BUT HE KNOWS HOW TO FIGHT.",
            "I like you boy.",
            "I need a good drink to help me sleep the night before a fight. You want some? I have a jug of sour goat's milk, stronger than any of that grape water you Southern twats like sucking on.",
            "I saw your pecker. What kind of god would have a pecker that small?",
            "I smell a crow",
            "I try not to think, walking is good, fighting is better , fucking is best. Thats my motto",
            "I want to make babies with her. Think of them... great big monsters. They'd conquer the world.",
            "I've always had blue eyes!",
            "I've had enough of the south, the women here dont like me",
            "LOOKS LIKE WE’RE THE NIGHT’S WATCH NOW.",
            "Most people that get bloody murdered, they *stay* that way. Not this one!",
            "my heart is broken",
            "No thanks I brought my own. **Glug** *chug* **Glug** *chug*",
            "Now which one of you cowards shit in my pants!",
            "Plenty of little men tried to put their swords through my heart. And there's plenty of little skeletons buried in the woods.",
            "Thats the kind of man he is. He is little but he is strong",
            "THE BIG WOMAN STILL HERE?",
            "They call me 'Giantsbane.' Want to know why? I killed a giant when I was 10. Then I climbed right into bed with his wife. When she woke up, you know what she did? Suckled me at her teat for three months. Thought I was her baby. That's how I got so strong. Giant's milk.",
            "They call you 'King Killer'",
            "We are all going to die, but at least we die together!",
            "We did it, we faced those icey fucks.  Looked right into their blue eyes and here we are",
            "What kind of person climbs on a dragon? A madman ... or a king!",
            "Which one of you cowards shit in my pants!",
            "You have to keep moving, that's the secret. Walking's good, fighting's better, fucking's best.",
            "You need to be patient. Give her time. Your cock shouldn't go near her till she's slick as a baby seal.",
            "You weigh as much as two fleas fucking",
            "'Your grace'? Did you hear that?",
            "You're the one they call the dog.",
            "You've got the north in you, the real north"
        ]
    },
    "tyrion-dwarfbot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("tyrion_client_id"),
                    client_secret=os.getenv("tyrion_client_secret"),
                    password=os.getenv("tyrion_password"),
                    user_agent=os.getenv("tyrion_user_agent"),
                    username=os.getenv("tyrion_username")
                ),
        "webhook": os.getenv("tyrion_webhook"),
        "keywords": ["tyrion","dwarf"],
        "subs": "FreeFolkSimulator",
        "db": "tyrion_comments",
        "quotes": [
            "(*SLAP*) One word and I'll hit you again.",
            "A day will come when you think you are safe and happy and your joy will turn to ashes in your mouth... and you will know the debt is paid.",
            "A wise man once said that the true history of the world is the history of great conversations in elegant rooms.",
            "A wise man once said that you should never believe a thing simply because you want to believe it.",
            "But what do I want? A little bloody gratitude would be a start.",
            "Cut off u/{}'s manhood and feed it to the goats!",
            "Death is so final, whereas life... ah, life is full of possibilities.",
            "Did I offend you? Sorry. You are the bastard, though.",
            "I could get essence of nightshade to help you sleep.",
            "I don't like threats.",
            "I don't like your beard...",
            "I don't pay you to put evil notions in my head. The ones already there don't need company.",
            "I have a tender spot in my heart for cripples, bastards and broken things.",
            "I imagined you'd be back at the brothel at this hour.",
            "I remember reading an old sailor's proverb, 'Piss on wildfire and your cock burns off'.",
            "I saved you. I saved this city and all your worthless lives! I should've let Stannis kill you all!",
            "I should never have told you about that.",
            "I think I would have remembered that.",
            "I was the smartest person I knew, certainly I had the wherewithal to unravel the mysteries that lay at the heart of u/{}.",
            "I WILL NOT GIVE MY LIFE FOR u/{}'S MURDER, AND I KNOW I'LL GET NO JUSTICE HERE!! SO I WILL LET THE GODS DECIDE MY FATE! I DEMAND A TRIAL BY COMBAT!!!",
            "I WISH I WAS THE MONSTER YOU THINK I AM!! I WISH I HAD ENOUGH POISON FOR THE WHOLE PACK OF YOU!! I WOULD GLADLY GIVE MY LIFE TO WATCH YOU ALL SWALLOW IT!!!",
            "I wish we could converse as two honest, intelligent men.",
            "I'd say you possess above average intelligence...",
            "If you want justice, you've come to the wrong place.",
            "If you’re going to be a cripple, it’s better to be a rich cripple.",
            "I'm here to help. Please don't eat the help.",
            "I'm not questioning your honour, u/{}...I'm denying its existence!",
            "I'm quite good at spending money, but a lifetime of outrageous wealth hasn't taught me about managing it!",
            "Is that supposed to make me feel better?",
            "It could get you killed. It could get me killed!",
            "It’s even better luck to suck a dwarf’s cock.",
            "It’s hard to put a leash on a dog once you’ve put a crown on its head.",
            "Just because I pay you for your services doesn’t diminish our friendship.",
            "Let us drink to our understanding.",
            "Let us sail on the tide of freedom instead of being drowned by it.",
            "Look at the fun we're having!",
            "Next time I have an idea like that, punch me in the face.",
            "Not this time. We’ll be staying at the finest castles and inns. No one turns away a Lannister.",
            "Oh, get on with it, you son of a whore...",
            "One Game at a time, my friend.",
            "So, should I turn around and close my eyes?",
            "Surely there are ways to have me killed that would be less detrimental to the war effort!",
            "Thank the gods.",
            "That would have made things so much easier.",
            "The charms of the North seem entirely lost on you.",
            "The future is shit, just like the past.",
            "The Lord of Light wants his enemies burned. The Drowned God wants them drowned. Why are all the gods such vicious cunts? Where is the god of tits and wine?",
            "Then there's really nothing else to say.",
            "Then you'll be fucking your own bride with a wooden cock!",
            "They say I'm half a man, but what does that make the lot of you?!",
            "They're starving, you fool! All because of the war you started!",
            "This one doesn't like me.",
            "Threaten me again and I'll have you thrown into the sea!",
            "Turns out, far too much has been written about great men and not nearly enough about morons. Doesn’t seem right.",
            "u/{}... I wish to confess. I wish to confess.",
            "Well... sooner or later, Cersei always gets what she wants.",
            "What did you once call me? A drunken little lust-filled beast?",
            "What do you want from me, u/{}? Gold? Women? Golden women? Stick with me and you'll have them all, for as long as I'm around and not a moment longer.",
            "When I was seven, I saw a servant girl bathing in the river. I stole her robe. She was forced to return to the castle naked and in tears. If I close my eyes, I can still see her tits bouncing.",
            "When I was twelve, I milked my eel into a pot of turtle stew. I flogged the one-eyed snake. I skinned my sausage. I made the bald man cry! Into the turtle stew, which I do believe my sister ate. At least I hope she did.",
            "Why do you care who I fuck?",
            "You and my family have more in common than you might admit.",
            "You have to admire u/{}'s imagination.",
            "You want revenge against the Lannisters? I killed my mother, Joanna Lannister, on the day I was born. I killed my father, Tywin Lannister, with a bolt to the heart. I am the greatest Lannister killer of our time.",
            "You're famous for fucking half of Westeros. You just arrived at the capital after two weeks of bad roads, where would you go?",
            "You're right, no point.",
            "You've forgotten the most important thing about whores...You don't buy them, you only rent them."
        ]
    },
    "night-king-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("nk_client_id"),
                    client_secret=os.getenv("nk_client_secret"),
                    password=os.getenv("nk_password"),
                    user_agent=os.getenv("nk_user_agent"),
                    username=os.getenv("nk_username")
                ),
        "webhook": os.getenv("nk_webhook"),
        "keywords": ["night king","white walkers"],
        "subs": "FreeFolkSimulator",
        "db": "nightking_comments",
        "quotes": [
            "*stares menacingly*",
            "*nefarious grinning*",
            "*angry scowl*",
            "*visible disinterest*",
            "*walks away unimpressed*",
            "*freezes infant baby*",
            "*slowly raises ice sword*",
            "*dead people begin rising*",
            "*angry zombie noises*",
            "*angry undead dragon noises*",
            "*visible boredom*",
            "*yells at flying crows*",
            "*ominous pointing*",
            "*Reanimates dead dragon*",
            "*aims ice spear*",
            "*HURLS ICE SPEAR*",
            "*EVIL SCREECHING*",
            "*shatters*"
        ]
    },
    "cersei-l-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("cersei_client_id"),
                    client_secret=os.getenv("cersei_client_secret"),
                    password=os.getenv("cersei_password"),
                    user_agent=os.getenv("cersei_user_agent"),
                    username=os.getenv("cersei_username")
                ),
        "webhook": os.getenv("cersei_webhook"),
        "keywords": ["cersei","cersi","bitch"],
        "subs": "FreeFolkSimulator",
        "db": "cersi_comments",
        "quotes": [
            "A disease doesn't decide to kill you—all the same you cut it out before it does.",
            "All we need is one good shot.",
            "Careful, Ser.",
            "Everyone who isn’t us, is an enemy.",
            "Ha, the people. You think I care?",
            "Have you bled yet?",
            "HAVE YOU LOST YOUR MIND? Let me go. You filthy… I am the queen! LET ME GO!",
            "HE SAW US!",
            "I can make sure you die in the most hideous way imaginable, and all I do is sit here imagining ways for you to die.",
            "I choose violence.",
            "I don’t know what you’re talking about.",
            "I don't care.",
            "I don't want to die.",
            "I fuck my brother because it feels good to feel him inside me.",
            "I have sinned. I see that now.",
            "I knew this would happen; the witch told me years ago.",
            "I made a terrible mistake; I carry it with me every single day.",
            "I shall wear this as a badge of honor.",
            "I thought if I could make something so good, so pure, maybe I’m not a monster.",
            "I want our baby to live.",
            "I wanted those elephants.",
            "I was lonely and afraid.",
            "If you ever call me sister again, I’ll have you strangled in your sleep.",
            "If you have any last words, now is the time.",
            "It doesn't make me feel anything.",
            "I've always wanted a dragon skull to decorate these halls.",
            "No one walks away from me.",
            "Nobody cares what your father once told you.",
            "OUT! All of you out.",
            "Please don't let me die.",
            "Power is power.",
            "Stay by my side.",
            "Such talent. You must make something for me.",
            "The children don't need to hear your filth.",
            "There's no need for such formalities.",
            "What could you possibly have done to warrant my forgiveness?",
            "When the war is won, the Lion shall rule the land, the Kraken shall rule the sea, and our child shall one day rule them all.",
            "You disappoint me, u/{}.",
            "You don’t need to be afraid of my father.",
            "You must be exhausted.",
            "You should be the Hand of the king.",
            "You want a whore—buy one.",
            "You’re upset—you’re not thinking clearly; I’ll visit again when you’ve had a chance to calm down.",
            "Your happiness is all I want in this world.",
            "You're dismissed.",
            "You're hurt.",
            "You're insolent; I have executed men for less.",
            "You're not boring, I'll give you that.",
        ]
    },
    "tywin-l-bot_": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("tywin_client_id"),
                    client_secret=os.getenv("tywin_client_secret"),
                    password=os.getenv("tywin_password"),
                    user_agent=os.getenv("tywin_user_agent"),
                    username=os.getenv("tywin_username")
                ),
        "webhook": os.getenv("tywin_webhook"),
        "keywords": ["tywin"],
        "subs": "FreeFolkSimulator",
        "db": "tywin_comments",
        "quotes": [
            "[*SKINS DEER*](https://i.gifer.com/BoVl.gif)",
            "[*You going to say something clever? Go on, say something clever*](https://imgur.com/gallery/8xeWHyK)",
            "A lion doesn't concern itself with the opinion of sheep.",
            "Any man who must say, 'I am the king' is no true king. I'll make sure you understand that when I've won your war for you.",
            "Careful now girl... I enjoy you but be careful",
            "Explain to me why it is more noble to kill ten thousand men in battle than a dozen at dinner.",
            "GO!! I'm sure your wife must miss you",
            "Here I stand, unarmed, unguarded, should I be concerned?",
            "I always thought you were a stunted fool, perhaps I was wrong",
            "I need you to become the man you're always meant to be. Not next year, not tomorrow... now",
            "I will let myself be consumed by maggots before mocking the family name and making you heir to Casterly Rock",
            "It's bad manners to refuse a lord's offer",
            "It's the family name that lives on, It's all that lives on",
            "Madness, madness and stupidity",
            "No that's not an opinion it's a fact",
            "NONSENSE YOU WILL MARRY u/{} AND THAT WILL BE THE END OF THAT!!",
            "Oh and one more thing... you will not take that whore to court, do you understand?",
            "The day you were born I wanted to carry you into the sea and let the waves wash you away",
            "This one's a girl you idiot",
            "What other brilliant insights have you brought me today?",
            "You are an ill-made, spiteful little creature full of envy, lust, and low cunning",
            "You are being counseled at this very moment",
            "You are done with whores. The next one I find in your bed, I'll hang.",
            "You ask that? You who killed your mother to come into the world?",
            "You spend too much time worrying what other people think of you",
            "You will wed her, bed her and put a child in her",
            "Your jokes are not appreciated",
            "You're too smart for your own good. Has anyone told you that?",
        ]
    },
    "jaime-l-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("jaime_client_id"),
                    client_secret=os.getenv("jaime_client_secret"),
                    password=os.getenv("jaime_password"),
                    user_agent=os.getenv("jaime_user_agent"),
                    username=os.getenv("jaime_username")
                ),
        "webhook": os.getenv("jaime_webhook"),
        "keywords": ["jaime","kingslayer"],
        "subs": "FreeFolkSimulator",
        "db": "jaime_comments",
        "quotes": [
            "Jaime. My name is Jaime.",
            "Are you sure we're not related? Ever since I've returned every Lannister I've seen has been a miserable pain in my ass. Maybe you're a Lannister too. You've got the hair for it, but not the looks.",
            "We don't get to choose who we love.",
            "It's a shame the throne isn't made out of cocks. They'd have never got him off it.",
            "Theres always lessons in failures.",
            "Tell Rob Stark I'm sorry I couldn't make his uncle's wedding. The Lannisters send their regards.",
            "It's a strange thing, the first time you cut a man. You realize we're nothing but sacks of meat, blood, and some bone to keep it all standing.",
            "You're much uglier in daylight.",
            "Only a fool makes threats he's not prepared to carry out.",
            "I'll remind you that our houses are at war. I'm sorry if this conflict has inconvenienced you, but rebelling against the crown does have consequences.",
            "Its a good thing I am who I am.",
            "Your childhood must have been awful for you. Were you a foot taller than all the boys? They laughed at you, called you names. Some boys like a challenge, one or two must have tried to get inside big Brienne.",
            "Now that we're speaking together man-to-man, I wonder if you need to keep me chained to this tree?",
        ]
    },
    "bobby-b-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("bobby_b_client_id"),
                    client_secret=os.getenv("bobby_b_client_secret"),
                    password=os.getenv("bobby_b_password"),
                    user_agent=os.getenv("bobby_b_user_agent"),
                    username=os.getenv("bobby_b_username")
                ),
        "webhook": os.getenv("bobby_b_webhook"),
        "keywords": ["bobby b", "bobby-b"],
        "subs": "FreeFolkSimulator",
        "db": "bobby_comments",
        "quotes": [
           "IS THAT HOW YOU SPEAK TO YOUR KING??",
           "YOU HEARD THE HAND, THE KING'S TOO FAT FOR HIS ARMOR! GO FIND THE BREASTPLATE STRETCHER! NOW!",
           "THE WHORE IS PREGNANT!",
           "[YOUR MOTHER WAS A DUMB WHORE WITH A FAT ARSE, DID YOU KNOW THAT?](https://i.imgur.com/g5SzSKk.gifv)",
           "[COME, BOW BEFORE YOUR KING! BOW, YA SHITS!](https://i.imgur.com/hrCP6Uk.gifv)",
           "GODS I WAS STRONG THEN",
           "START THE DAMN JOUST BEFORE I PISS MESELF!",
           "STOP THIS MADNESS, IN THE NAME OF YOUR KING!",
           "A DOTHRAKI HORDE ON AN OPEN FIELD, {}!",
           "GODS WHAT A STUPID NAME!",
           "WINE! WINE! MOOOOOOOOAR WINE!",
           "THANK THE GODS FOR BESSIE AND HER TITS",
           "YOU GOT FAT!",
           "THERE'S A WAR COMING, NED. I DON'T KNOW WHEN, I DON'T KNOW WHO WE'LL BE FIGHTING...BUT IT'S COMING!",
           "OH, IT'S UNSPEAKABLE TO YOU? WHAT HER FATHER DID TO YOUR FAMILY, THAT WAS UNSPEAKABLE!",
           "SOON ENOUGH, THAT CHILD WILL SPREAD HER LEGS AND START BREEDING!",
           "DO YOU THINK IT'S HONOR THAT'S KEEPING THE PEACE?! IT'S FEAR! FEAR AND BLOOD!",
           "CAREFUL, {}! CAREFUL NOW!",
           "YOU'RE MY COUNCIL, COUNSEL! SPEAK SENSE TO THIS HONORABLE FOOL!",
           "YOU'RE THE KING'S HAND! YOU'LL DO AS I COMMAND, OR I'LL FIND ME A HAND WHO WILL!",
           "OUT! OUT, DAMN YOU! I'M DONE WITH YOU! GO, RUN BACK TO WINTERFELL! I'LL HAVE YOUR HEAD ON A SPIKE!",
           "HOLD YOUR TONGUE!",
           "WEAR IT IN SILENCE, OR I'LL HONOR YOU AGAIN!",
           "PISS ON THAT! SEND A RAVEN! I WANT YOU TO STAY! I'M THE KING, I GET WHAT I WANT!",
           "WHO NAMED YOU? SOME HALFWIT WITH A STUTTER??",
           "IS THAT WHAT EMPTY MEANS??",
           "I WARNED YOU THIS WOULD HAPPEN! BACK IN THE NORTH, I WARNED YOU, BUT YOU DIDN'T CARE TO HEAR! WELL, HEAR IT NOW!",
           "WHY HAVE I NOT SEEN YOU? WHERE THE HELL HAVE YOU BEEN?",
           "I'VE GOT SEVEN KINGDOMS TO RULE! ONE KING, SEVEN KINGDOMS!",
           "MY, YOU'RE A PRETTY ONE! AND YOUR NAME IS?",
           "OHHH, SHOW US YOUR MUSCLES! YOU'LL BE A SOLDIER!",
           "TAKE ME TO YOUR CRYPT, I WANT TO PAY MY RESPECTS!",
           "WE WERE AT WAR! NONE OF US KNEW IF WE WERE GONNA GO BACK HOME AGAIN!",
           "THEY NEVER TELL YOU HOW THEY ALL SHIT THEMSELVES! THEY DON'T PUT THAT PART IN THE SONGS!",
           "YOU EVER FUCK A RIVERLANDS GIRL, {}?",
           "YES, IT'S BEEN A LONG TIME... BUT I STILL REMEMBER EVERY FACE!",
           "STUPID BOY!",
           "HE COULD HAVE LINGERED ON THE EDGE OF THE BATTLE WITH THE SMART BOYS, AND TODAY HIS WIFE WOULD BE MAKING HIM MISERABLE, HIS SONS WOULD BE INGRATES, AND HE WOULD BE WAKING THREE TIMES IN THE NIGHT TO PISS INTO A BOWL!",
           "SURROUNDED BY LANNISTERS! EVERY TIME I CLOSE MY EYES I SEE THEIR BLONDE HAIR AND THEIR SMUG, SATISFIED FACES!",
           "IT MUST WOUND YOUR PRIDE! STANDING OUT THERE, LIKE A GLORIFIED SENTRY!",
           "FORCED TO MIND THE DOOR WHILE YOUR KING EATS AND DRINKS AND SHITS AND FUCKS!",
           "WE'RE TELLING WAR STORIES! WHO WAS YOUR FIRST KILL, NOT COUNTING OLD MEN?",
           "DID YOU EVER MAKE THE EIGHT?",
           "EASY, BOY! YOU MIGHT BE MY BROTHER BUT YOU'RE SPEAKING TO THE KING!",
           "DID YOU HAVE TO BURY HER IN A PLACE LIKE THIS?",
           "SHE BELONGED WITH ME!",
           "SHE SHOULD BE ON A HILL SOMEWHERE WITH THE SUN AND THE CLOUDS ABOVE HER!",
           "YOU LET THAT LITTLE GIRL DISARM YOU?",
           "I'M NOT TRYING TO HONOR YOU, I'M TRYING TO GET YOU TO RUN MY KINGDOM WHILE I EAT, DRINK AND WHORE MY WAY TO AN EARLY GRAVE!",
           "THAT'S ALL WHAT THE REALM IS NOW. BACKSTABBING AND SCHEMING AND ARSE-LICKING AND MONEY-GRUBBING!",
           "ALL I WANTED TO DO WAS CRACK SKULLS AND FUCK GIRLS!",
           "IN MY DREAMS, I KILL HIM EVERY NIGHT!",
           "YOU HELPED ME WIN THE IRON THRONE, NOW HELP ME KEEP THE DAMN THING! WE WERE MEANT TO RULE TOGETHER!",
           "I THOUGHT BEING KING MEANT I COULD DO WHATEVER I WANTED!",
           "IT'S A GREAT CRIME TO LIE TO A KING!",
           "THE GODS MOCK THE PRAYERS OF KINGS AND COWHERDS ALIKE!",
           "BACKSTABBING DOESN'T PREPARE YOU FOR A FIGHT!",
           "DRINK AND STAY QUIET, THE KING IS TALKING!",
           "I WAS NEVER SO ALIVE AS WHEN I WAS WINNING THIS THRONE, OR SO DEAD AS NOW THAT I'VE WON IT!",
           "GIVE ME SOMETHING FOR THE PAIN AND LET ME DIE!",
           "I ASK YOU, {}, WHAT GOOD IS IT TO WEAR A CROWN?",
           "THE GODS BE DAMNED! IT WAS A HOLLOW VICTORY THEY GAVE ME!",
           "I SIT ON THE DAMN IRON SEAT WHEN I MUST. DOES THAT MEAN I DON'T HAVE THE SAME HUNGERS AS OTHER MEN?",
           "A BIT OF WINE NOW AND AGAIN, A GIRL SQUEALING IN BED, THE FEEL OF A HORSE BETWEEN MY LEGS?",
           "SEVEN HELLS, {}, I WANT TO HIT SOMEONE!",
           "MORE THAN ONCE, I HAVE DREAMED OF GIVING UP THE CROWN!",
           "TAKE SHIP FOR THE FREE CITIES WITH MY HORSE AND MY HAMMER, SPEND MY TIME WARRING AND WHORING, THAT’S WHAT I WAS MADE FOR!",
           "THE SELLSWORD KING, HOW THE SINGERS WOULD LOVE ME!"
        ]
    },
    "gimli-g-bot": {
        "reddit": praw.Reddit(
            client_id=os.getenv("gimli_client_id"),
            client_secret=os.getenv("gimli_client_secret"),
            password=os.getenv("gimli_password"),
            user_agent=os.getenv("gimli_user_agent"),
            username=os.getenv("gimli_username")
        ),
        "webhook": os.getenv("gimli_webhook"),
        "keywords": ["gimli","dwarf"],
        "subs": "FreeFolkSimulator",
        "db": "gimli_comments",
        "quotes": [
            "THERE'S PLENTY FOR THE BOTH OF US! MAY THE BEST DWARF WIN!",
            "AND I SUPPOSE YOU THINK YOU ARE THE ONE TO DO IT!",
            "AND MY AXE!",
            "AND YOU KNOW WHAT THIS DWARF SAYS TO THAT? ISHKHAQWI AI DURUGNUL!",
            "AYE, I COULD DO THAT!",
            "BRING YOUR PRETTY FACE TO MY AXE!",
            "CERTAINTY OF DEATH! SMALL CHANCE OF SUCCESS! WHAT ARE WE WAITING FOR?",
            "DON'T TELL THE ELF!",
            "GIVE ME YOUR NAME HORSE-MASTER, AND I SHALL GIVE YOU MINE!",
            "HAMMER AND TONGS! I AM SO TORN BETWEEN RAGE AND JOY, THAT IF I DO NOT BURST, IT WILL BE A MARVEL!",
            "HE WAS TWITCHING BECAUSE HE'S GOT MY AXE EMBEDDED IN HIS NERVOUS SYSTEM!",
            "I GUESS THAT CONCLUDES NEGOTIATIONS!",
            "I HAVE BEEN DEALT A WOUND BEYOND ALL HEALING, FOR I HAVE LOOKED THE LAST UPON THAT WHICH WAS FAIREST!",
            "I WILL BE DEAD BEFORE I SEE THE RING IN THE HANDS OF AN ELF! NEVER TRUST AN ELF!",
            "I'M WASTED ON CROSS COUNTRY! WE DWARVES ARE NATURAL SPRINTERS, VERY DANGEROUS OVER SHORT DISTANCES!",
            "IT'S TRUE YOU DON'T SEE MANY DWARF WOMEN! AND IN FACT, THEY ARE SO ALIKE IN VOICE AND APPEARANCE THAT THEY ARE OFTEN MISTAKEN FOR DWARF MEN!",
            "KEEP BREATHING! THAT'S THE KEY: BREATHE!",
            "LET THEM COME! THERE IS ONE DWARF YET IN MORIA WHO STILL DRAWS BREATH!",
            "LET'S JUST HAVE HIS HEAD AND BE DONE WITH IT!",
            "NEVER THOUGHT I'D DIE FIGHTING SIDE BY SIDE WITH AN ELF!",
            "NOBODY TOSSES A DWARF!",
            "NOT THE BEARD!",
            "OH COME ON, WE CAN TAKE 'EM!",
            "OH! THAT'S IT, RIGHT! WE WARNED YOU! PREPARE TO BE BOARDED!",
            "SALTED PORK?",
            "SOON, MASTER ELF, YOU WILL ENJOY THE FABLED HOSPITALITY OF THE DWARVES! ROARING FIRES, MALT BEER, RED MEAT OFF THE BONE!",
            "SPEAK WORDS WE CAN ALL UNDERSTAND!",
            "THAT ONE COUNTS AS MINE!",
            "THAT STILL ONLY COUNTS AS ONE!",
            "THAT WAS DELIBERATE! IT WAS DELIBERATE!",
            "THEN WHAT ARE WE WAITING FOR?",
            "THEY HAD NO HONOR IN LIFE! THEY HAVE NONE NOW IN DEATH!",
            "THIS NEW GANDALF IS MORE GRUMPY THAN THE OLD ONE!",
            "TOSS ME! I CANNOT JUMP THE DISTANCE, YOU'LL HAVE TO TOSS ME!",
            "WELL HERE'S ONE DWARF SHE WON'T ENSNARE SO EASILY! I HAVE THE EYES OF A HAWK AND THE EARS OF A FOX!",
            "WELL THIS IS A THING UNHEARD OF! AN ELF WOULD GO UNDERGROUND WHERE A DWARF DARE NOT! OH I'D NEVER HEAR THE END OF IT!",
            "WHATEVER LUCK YOU LIVE BY, LET'S HOPE IT LASTS THE NIGHT!",
            "WHAT'S HAPPENING OUT THERE?",
            "YOU ARE FULL OF SURPRISES, MASTER BAGGINS!",
            "YOU ARE THE LUCKIEST, THE CUNNINGEST, AND MOST RECKLESS MAN I EVER KNEW!",
            "YOU COULD HAVE PICKED A BETTER SPOT!",
            "YOU YOUNG RASCALS! A MERRY HUNT YOU'VE LED US ON, AND NOW WE FIND YOU FEASTING AND SMOKING!",
            "YOU'LL FIND MORE CHEER IN A GRAVEYARD!",
        ]
    },
    "arya-s-bot": {
        "reddit": praw.Reddit(
            client_id=os.getenv("arya_client_id"),
            client_secret=os.getenv("arya_client_secret"),
            password=os.getenv("arya_password"),
            user_agent=os.getenv("arya_user_agent"),
            username=os.getenv("arya_username")
        ),
        "webhook": os.getenv("arya_webhook"),
        "keywords": ["arya"],
        "subs": "FreeFolkSimulator",
        "db": "arya_comments",
        "quotes": [
            "We had to throw rocks. I told her to run, to go be free, that I didn't want her anymore. There were other wolves for her to play with, we heard them howling, and Jory said the woods were full of game, so she'd have deer to hunt. Only she kept following and finally we had to throw rocks. I hit her twice. She whined and looked at me and I felt so 'shamed, but it was right, wasn't it? The queen would have killed her.",
            "Valar Dohaeris.",
            "**Cersei**...**Beric Dondarrion**...**Illyn Payne**...**The Mountain**...**The Red Woman**...~~Thoros of Myr~~...~~Joffrey~~...~~Polliver~~...~~Walder Frey~~...~~Meryn Trant~~...~~Tywin Lannister~~...~~Rorge~~...~~The Høund~~...",
            "Can't wait to hear what Bobby B has to say about this!",
            "Someday I'm going to put a sword through your eye and out the back of your skull.",
            "Leave one wolf alive and the sheep are never safe.",
            "Not if they lose their heads first.",
            "I can't sleep until I say the names.",
            "I'm going to kill the queen.",
            "If you could only see the beast you made of me...",
            "Leave one wolf alive and the sheep are never safe. When people ask you what happened here, tell them the North remembers. Tell them winter came for House Frey.",
            "Tell them the North remembers. Tell them winter came for House Frey.",
            "Face, tits, balls, I hit 'em right where I wanted to.",
            "Only the ones I'm going to kill.",
            "Nymeria? Nymeria, it’s me, Arya. I’m heading north, girl. Back to Winterfell. I’m finally going home. Come with me. Come with me.",
            "Anyone can be killed.",
            "That's not you.",
            "You’d be like a kitten to him. He’d kill you with his little finger.",
            "Where is Nymeria?",
            "I know which end to use.",
            "**Cersei**...**Beric Dondarrion**...**Illyn Payne**...**The Mountain**...**The Red Woman**...~~Joffrey~~...~~Polliver~~...~~Thoros of Myr~~...~~Walder Frey~~...~~Meryn Trant~~...~~Tywin Lannister~~...~~Rorge~~...~~The Hound~~...",
            "All of you better run or my brother will kill you, he's a Stark. He's more wolf than man, and so am I.",
            "**Cersei**...**Beric Dondarrion**...**Illyn Payne**...**The Mountain**...**The Red Woman**...~~Thoros of Myr~~...~~Joffrey~~...~~Polliver~~...~~Walder Frey~~...~~Meryn Trant~~...~~Tywin Lannister~~...~~Rorge~~...~~The Hound~~...",
            "My name is Arya Stark. I want you to know that the last thing you're ever going to see is a Stark, smiling down at you, as you die.",
            "Valar Morghulis.",
            "I am not a boy, I am Arya Stark of Winterfell and if you lay a hand on me my father will have both of your heads on spikes.",
            "Nothing isn't better or worse than anything. Nothing is just nothing.",
            "Do I have to call you Lady Stark now?",
        ]
    },
    "bran_bot_": {
        "reddit": praw.Reddit(
            client_id=os.getenv("bran_client_id"),
            client_secret=os.getenv("bran_client_secret"),
            password=os.getenv("bran_password"),
            user_agent=os.getenv("bran_user_agent"),
            username=os.getenv("bran_username")
        ),
        "webhook": os.getenv("bran_webhook"),
        "keywords": ["bran", "dumbfuckery"],
        "subs": "FreeFolkSimulator",
        "db": "bran_comments",
        "quotes": [
            "His mark is on me, he know where I am",
            "I’m the three eyed raven.",
            "We don’t have time for this. The Night King is approaching",
            "I rather be dead.",
            "You shouldn't envy me. Mostly I live in the past",
            "The things we do for love O_O",
            "You looked beatiful on your wedding night",
            "You finally show me something I care about and your drag me away",
            "You're going to help me walk again?",
            "Is your choice",
            "Almost",
            "Hodor",
            "We have time for this",
            "It Means I Can See Everything, Everything That's Ever Happened To Everyone. Everything That's Happening Right Now O_O.",
            "I don't know, no one has ever done that",
            "I am sorry for all that's happened to you",
            "You looked beautiful on your wedding night O_O",
            "I want Doran Martell's wheelchair",
            "Robert's Rebellion was based on a lie, Rhaegar didn't kidnapped my aunt or raped her, He loved her. And she loved him.",
            "It’s wasted on a cripple.",
            "*stares*",
            "I am waiting for an old friend",
            "He needs to know O_O.",
            "We have to tell him .",
            "Chaos is a ladder",
            "I don't know, no one has ever tried",
            "The strongest trees are rooted in the dark places of the earth. Darkness will be your cloak, your shield, your mother's milk. Darkness will make you strong",
            "You are a good man",
            " I see you're a kneeler",
            "Jon loves his queen",
            "Thank you",
            "I will be at the Godswood",
            "It Means I Can See Everything, Everything That's Ever Happened To Everyone. Everything That's Happening Right Now.",
            " I see you're a kneeler O_O",
            "He needs to know.",

        ]
    },
    "eddie-s-bot": {
        "reddit": praw.Reddit(
            client_id=os.getenv("eddie_client_id"),
            client_secret=os.getenv("eddie_client_secret"),
            password=os.getenv("eddie_password"),
            user_agent=os.getenv("eddie_user_agent"),
            username=os.getenv("eddie_username")
        ),
        "webhook": os.getenv("eddie_webhook"),
        "keywords": ["eddie s", "eddard", "house stark"],
        "subs": "FreeFolkSimulator",
        "db": "eddie_comments",
        "quotes": [
            "Tell me we're not speaking of this.",
            "You will dishonor yourself forever if you do this.",
            "Even a million Dothraki are no threat to the realm, as long as they remain on the other side of the Narrow Sea. They have no ships, u/{}.",
            "I followed you into war. Twice. Without doubts, without second thoughts. But I will not follow you now. The u/{} I grew up with didn't tremble at the shadow of an unborn child.",
            "Then we're no better than the Mad King.",
            "I will have no part in it.",
            "No. Now it ends.",
            "The breastplate stretcher?",
            "Grand Master u/{}. Send a raven to Casterly Rock. Inform Tywin Lannister that he has been summoned to Court to answer for the crimes of his bannermen. He will arrive within the fortnight or be branded an enemy of the crown and a traitor to the realm.",
            "And good luck to him. I thought you were a better man.",
            "She was my sister. This is where she belongs.",
            "I'm not thirsty.",
        ]
    },

}