import praw
import os
from dotenv import load_dotenv

load_dotenv()


config = {
    "vizzy-t-bot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("vizzy_client_id"),
                    client_secret=os.getenv("vizzy_client_secret"),
                    password=os.getenv("vizzy_password"),
                    user_agent=os.getenv("vizzy_user_agent"),
                    username=os.getenv("vizzy_username")
                ),
        "webhook": os.getenv("vizzy_webhook"),
        "keywords": ["vizzy t", "vissy t"],
        "subs": "FreeFolkSimulator",
        "db": "vizzy_comments",
        "quotes": [
            "(WHEEZES) (GROANS) (LABORED BREATHING) ",
            "A MOST JUDICIOUS PROPOSITION!",
            "GODS BE GOOD!!",
            "MY WIFE AND SON ARE DEAD!  I WILL NOT SIT HERE AND SUFFER CROWS THAT COME TO FEAST ON THEIR CORPSES!",
            "NOW THAT IS A NAME FIT FOR A KING!",
            "OTTO HIGHTOWER IS A MORE HONORABLE MAN THAN YOU COULD EVER BE!",
            "WHY DO YOU CUT ME SO DEEPLY?",
            "WE ARE A FAMILY!",
            "WHAT LORD WOULD WED HER NOW?  IN THIS CONDITION!?",
            "WHERE DID YOU HEAR SUCH CALUMNIES?  {}!  TELL ME THE TRUTH OF IT!",
            "WHERE DID YOU HEAR THIS?!",
            "WHERE IN THE SEVEN HELLS IS RHAENYRA?!",
            "WOULD YOU LIKE TO SEE THE TAPESTRIES!?",
            "YOU WILL ADDRESS ME AS 'YOUR GRACE', OR I WILL HAVE MY KINGSGUARD CUT OUT YOUR TONGUE!",
            "YOUR FATHER, YOUR GRANDSIRE, YOUR KING DEMANDS IT.",
            "YOUR KING DEMANDS AN ANSWER!  WHO SPOKE THESE LIES TO YOU?!",
            "I CAME HERE TO HUNT, NOT TO BE SUFFOCATED BY ALL THIS FUCKING POLITICKING!",
            "EVEN I DO NOT EXIST ABOVE TRADITION AND DUTY, {}!",
            "*I would be delighted!*",
            "I WILL SIT THE THRONE TODAY.",
            "INSTEAD OF BEING BY MY SIDE, YOU CHOSE TO CELEBRATE YOUR OWN RISE, LAUGHING WITH YOUR WHORES AND YOUR LICKSPITTLES!",
            "MY HEIR WILL SOON PUT ALL OF THIS DAMNABLE HAND-WRINGING TO REST HIMSELF!",
            "I WILL NOT BE MADE TO CHOOSE BETWEEN MY BROTHER AND MY DAUGHTER!",
            "*I WILL HAVE YOUR TONGUE FOR THAT!*",
            "DAEMON IS MY BROTHER.  MY BLOOD.  AND HE WILL HAVE HIS PLACE AT MY COURT!",
            "*A dragon's saddle is one thing, but the Iron Throne is the most dangerous seat in the realm.*",
            "*A truly great Targaryen King I am. Powerless over mine own daughter of seven and ten.*",
            "*Be welcome! I know many of you have traveled long leagues to be at these games. But I promise, you will not be disappointed!*",
            "*Daemon was not made to wear the crown. But I believe that you were, {}.*",
            "*Don't be scared. They're going to bring the babe out.*",
            "*I did not decide to name Rhaenyra my heir on a whim. All the lord of the kingdom would do well to remember that.* ",
            "*You are the very best of your mother. And I believe it, I know she did, that you could be a great ruling queen.*",
            "*I must... admit... my confusion.  I do not understand why petitions are being heard over a settled succession.* ",
            "*I will not cloud my mind. I must put things right.*",
            "*I'm glad we could meet. I know tempers ran hot today, and I wanted to assure you how much I value the bond between our houses.*",
            "*I'm going to bed, {}.*",
            "What is your advice, dear {}?",
            "She's twelve!",
            "Ever since my name was read by the archmaesters at the Great Council, I have felt Corlys Velaryon's envious gaze staring at me from across the Blackwater.",
            "*It both gladdens my heart and fills me with sorrow to see these faces around the table.*",
            "*Let us no longer hold ill feelings in our hearts. The crown cannot stand strong if the House of the Dragon remains divided.*",
            "*Mayhaps we can turn our attentions towards happier pursuits.*",
            "*{} was a strong Lord Commander of the Kingsguard. But he was ill for some time. He passed in peace, I hope.*",
            "*That man's pride has pride.*",
            "*The boy just turned two, {}...*",
            "This is a lie. You have been lied to.",
            "WHO IS RESPONSIBLE FOR THIS GOSSIP? HAVE THIS RUMORMONGER BROUGHT BEFORE ME AT ONCE AND I WILL TAKE THEIR EYES!",
            "You think yourself a cunning man. Your designs are obvious.",
            "*The Gods punish me for my indulgences.*",
            "*The Iron Throne is the most dangerous seat in the realm.* ",
            "*The King's cupbearer must not be late. Leaves people wanting for cups.*",
            "*The tourney will take the better part of a week. Before the games are over, my son will be born, and the whole realm will celebrate.*",
            "*The truth does not matter, {}. Only perception.*",
            "*Then he will be loved and cherished.*",
            "*So I said to him, 'I believe you may be looking up the wrong end'*",
            "*There are times when I would rather face the black dread himself than mine own daughter of seven and ten.*",
            "*There's a boy in the Queen's belly. I know it.*",
            "**THIS INTERMINABLE INFIGHTING MUST CEASE, ALL OF YOU!**",
            "*This is an occasion for celebration, it seems.*",
            "*I had a black mare once. Black like a raven. One day, she escaped her pasture and he neighboring stallion sired a foal on her. The stallion was as silver as the moon on a winter's night and the foal, when it was born, chestnut. Just the most unremarkable brown horse you ever saw. Nature is a thing of mysterious works.*",
            "*Tongues will not change the succession, let them wag.*",
            "*Well... the matter is settled.  Again.  I hereby reaffirm Prince Lucerys of House Velaryon as heir to Driftmark, the Driftwood Throne, and the next Lord of the Tides. (WHEEZING)*",
            "*What are you saying? My brother would murder me, take my crown? Are you?!*",
            "*Would you like to see the tapestries?*",
            "*You are my political headache.*",
            "*You are to return to Runestone and your lady wife at once, and you are to do so without quarrel by order of your King.*",
            "YOU SPEND MORE TIME IN THAT BATH THAN I DO ON THE THRONE!",
            "*Your mother's absence is a wound that will never heal. Without her, the Red Keep has lost a warmth that I dare say it will never recover.*"
        ]
    },

    "tyrion-dwarfbot": {
        "reddit": praw.Reddit(
                    client_id=os.getenv("tyrion_client_id"),
                    client_secret=os.getenv("tyrion_client_secret"),
                    password=os.getenv("tyrion_password"),
                    user_agent=os.getenv("tyrion_user_agent"),
                    username=os.getenv("tyrion_username")
                ),
        "webhook": os.getenv("tyrion_webhook"),
        "keywords": ["tyrion","dwarf"],
        "subs": "FreeFolkSimulator",
        "db": "tyrion_comments",
        "quotes": [
            "(*SLAP*) One word and I'll hit you again.",
            "A day will come when you think you are safe and happy and your joy will turn to ashes in your mouth... and you will know the debt is paid.",
            "A wise man once said that the true history of the world is the history of great conversations in elegant rooms.",
            "A wise man once said that you should never believe a thing simply because you want to believe it.",
            "But what do I want? A little bloody gratitude would be a start.",
            "Cut off u/{}'s manhood and feed it to the goats!",
            "Death is so final, whereas life... ah, life is full of possibilities.",
            "Did I offend you? Sorry. You are the bastard, though.",
            "I could get essence of nightshade to help you sleep.",
            "I don't like threats.",
            "I don't like your beard...",
            "I don't pay you to put evil notions in my head. The ones already there don't need company.",
            "I have a tender spot in my heart for cripples, bastards and broken things.",
            "I imagined you'd be back at the brothel at this hour.",
            "I remember reading an .old sailor's proverb, 'Piss on wildfire and your cock burns off'.",
            "I saved you. I saved this city and all your worthless lives! I should've let Stannis kill you all!",
            "I should never have told you about that.",
            "I think I would have remembered that.",
            "I was the smartest person I knew, certainly I had the wherewithal to unravel the mysteries that lay at the heart of u/{}.",
            "I WILL NOT GIVE MY LIFE FOR u/{}'S MURDER, AND I KNOW I'LL GET NO JUSTICE HERE!! SO I WILL LET THE GODS DECIDE MY FATE! I DEMAND A TRIAL BY COMBAT!!!",
            "I WISH I WAS THE MONSTER YOU THINK I AM!! I WISH I HAD ENOUGH POISON FOR THE WHOLE PACK OF YOU!! I WOULD GLADLY GIVE MY LIFE TO WATCH YOU ALL SWALLOW IT!!!",
            "I wish we could converse as two honest, intelligent men.",
            "I'd say you possess above average intelligence...",
            "If you want justice, you've come to the wrong place.",
            "If you’re going to be a cripple, it’s better to be a rich cripple.",
            "I'm here to help. Please don't eat the help.",
            "I'm not questioning your honour, u/{}...I'm denying its existence!",
            "I'm quite good at spending money, but a lifetime of outrageous wealth hasn't taught me about managing it!",
            "Is that supposed to make me feel better?",
            "It could get you killed. It could get me killed!",
            "It’s even better luck to suck a dwarf’s cock.",
            "It’s hard to put a leash on a dog once you’ve put a crown on its head.",
            "Just because I pay you for your services doesn’t diminish our friendship.",
            "Let us drink to our understanding.",
            "Let us sail on the tide of freedom instead of being drowned by it.",
            "Look at the fun we're having!",
            "Next time I have an idea like that, punch me in the face.",
            "Not this time. We’ll be staying at the finest castles and inns. No one turns away a Lannister.",
            "Oh, get on with it, you son of a whore...",
            "One Game at a time, my friend.",
            "So, should I turn around and close my eyes?",
            "Surely there are ways to have me killed that would be less detrimental to the war effort!",
            "Thank the gods.",
            "That would have made things so much easier.",
            "The charms of the North seem entirely lost on you.",
            "The future is shit, just like the past.",
            "The Lord of Light wants his enemies burned. The Drowned God wants them drowned. Why are all the gods such vicious cunts? Where is the god of tits and wine?",
            "Then there's really nothing else to say.",
            "Then you'll be fucking your own bride with a wooden cock!",
            "They say I'm half a man, but what does that make the lot of you?!",
            "They're starving, you fool! All because of the war you started!",
            "This one doesn't like me.",
            "Threaten me again and I'll have you thrown into the sea!",
            "Turns out, far too much has been written about great men and not nearly enough about morons. Doesn’t seem right.",
            "u/{}... I wish to confess. I wish to confess.",
            "Well... sooner or later, Cersei always gets what she wants.",
            "What did you once call me? A drunken little lust-filled beast?",
            "What do you want from me, u/{}? Gold? Women? Golden women? Stick with me and you'll have them all, for as long as I'm around and not a moment longer.",
            "When I was seven, I saw a servant girl bathing in the river. I stole her robe. She was forced to return to the castle naked and in tears. If I close my eyes, I can still see her tits bouncing.",
            "When I was twelve, I milked my eel into a pot of turtle stew. I flogged the one-eyed snake. I skinned my sausage. I made the bald man cry! Into the turtle stew, which I do believe my sister ate. At least I hope she did.",
            "Why do you care who I fuck?",
            "You and my family have more in common than you might admit.",
            "You have to admire u/{}'s imagination.",
            "You want revenge against the Lannisters? I killed my mother, Joanna Lannister, on the day I was born. I killed my father, Tywin Lannister, with a bolt to the heart. I am the greatest Lannister killer of our time.",
            "You're famous for fucking half of Westeros. You just arrived at the capital after two weeks of bad roads, where would you go?",
            "You're right, no point.",
            "You've forgotten the most important thing about whores...You don't buy them, you only rent them."
        ]
    },



}